In [10]:
import pandas
import html5lib

Rain_Sydney = pandas.read_html('http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_nccObsCode=136&p_display_type=dailyDataFile&p_startYear=2016&p_c=-872837665&p_stn_num=066062'
                 ,header = 0, index_col = 0)
Rain_Sydney

[                 Jan   Feb    Mar    Apr  May    Jun    Jul    Aug   Sep  \
 2016
 Graph            NaN   NaN    NaN    NaN  NaN    NaN    NaN    NaN   NaN
 1st              0.0   0.2    0.0    0.0  2.8   29.4    0.0    0.0   0.0
 2nd              0.0   2.0    0.0    0.0  0.0    1.0    0.0    0.4  14.4
 3rd              0.0   0.0    0.0    0.0  0.0    0.2    0.0   24.8  23.4
 4th             15.0  10.8    0.0   94.4  0.0   64.4    0.0   61.0   0.0
 5th             34.2   3.6    0.0    6.4  0.0   93.8    4.8    4.0   0.0
 6th             51.4   1.8    0.0    0.0  0.0   68.4    0.2    1.8   0.0
 7th             41.4   0.0    0.0    0.2  0.0    0.0   29.4    0.6   0.0
 8th              0.4   0.0    0.0    0.0  0.0    0.0   22.4    0.0   0.0
 9th              0.0   0.0    0.0    0.4  1.6    0.2    2.2    0.0   0.0
 10th             0.0   0.2    0.0    0.0  0.0    0.2    1.0    0.0   1.2
 11th             0.0   0.0    0.0    0.0  0.0    0.0    0.0    0.0   0.0
 12th             0.0   0.0    0.0    8.2  0.0    0.0    0.2    0.0   0.0
 13th             0.0   0.0    0.0    0.6  0.0    0.0    0.0    0.0   0.0
 14th             0.0   0.0    0.0    0.6  0.0    0.0    0.0    0.0   5.8
 15th            34.0   0.0   16.8    1.0  0.0    0.0    0.0    0.0   0.0
 16th             5.4   0.0   23.0    0.0  0.0    0.0    0.0    0.0   0.0
 17th             0.0   0.0   13.6    0.0  0.0    0.0    0.8    0.0   0.0
 18th             0.0   0.0    3.4    2.0  0.0    5.0    0.0    0.0   0.0
 19th             0.0   0.0    4.8   15.0  0.0    0.4    0.2    0.0  13.4
 20th             0.0   0.0    0.2   15.8  0.0   38.8   17.0    0.4   0.0
 21st             0.0   6.0   61.2    0.0  0.0    0.0   20.4    0.0   0.0
 22nd            30.6   1.2   25.4    0.0  0.0    0.0    0.0    0.0   2.0
 23rd            13.0   0.0    1.6    6.6  0.0    0.0    6.0    1.8   0.6
 24th             0.0   0.0    0.0    3.8  0.0    0.0    0.0    2.4   0.0
 25th             0.0   0.0    0.0    0.0  0.0    0.6    0.0   52.8   3.4
 26th             0.0   0.0    0.0    0.0  0.2    0.0    0.0    0.0   4.0
 27th             2.2   0.0    0.2    0.0  0.2    0.0    0.0    1.4   0.0
 28th             0.4   0.0   34.8    0.0  0.0    2.4    0.0    0.0   0.0
 29th             0.0   0.0    0.0    0.0  2.2    0.2    0.0    0.0   1.4
 30th             9.0   NaN    7.0    0.0  0.2    0.0    0.0    0.0   0.4
 31st            12.8   NaN    1.2    NaN  0.0    NaN    0.0    0.0   NaN
 Highest Daily   51.4  10.8   61.2   94.4  2.8   93.8   29.4   61.0  23.4
 Monthly Total  249.8  25.8  193.2  155.0  7.2  305.0  104.6  151.4  70.0

                 Oct   Nov   Dec
 2016
 Graph           NaN   NaN   NaN
 1st             0.0   0.0   0.0
 2nd             0.0   0.0   0.2
 3rd             0.0   0.0   0.0
 4th             0.0   0.0   0.0
 5th             0.0   0.0   0.4
 6th             0.0   0.0   3.2
 7th             0.0   0.0   7.8
 8th             0.2   0.0   0.2
 9th             0.0   2.0   0.4
 10th            0.0  10.2   0.0
 11th            3.8   0.0   0.0
 12th            0.0   9.0   0.0
 13th            4.4   0.0   0.0
 14th            0.2   0.0   0.0
 15th            0.0   0.6   8.2
 16th            0.0   0.0  32.6
 17th            0.0   0.0  10.4
 18th            3.0   0.0   0.0
 19th            0.2   0.0   0.0
 20th            0.0   0.0   0.0
 21st            0.0   0.0   0.0
 22nd           11.8   0.0   0.0
 23rd            0.6   0.0   0.0
 24th            0.8   5.4   0.0
 25th            0.0   0.0   1.6
 26th            0.0   0.0   0.0
 27th            0.0   0.0   0.0
 28th            1.4   0.0   0.0
 29th            3.2   0.0   0.0
 30th            0.2   0.0   0.0
 31st            1.6   NaN   0.0
 Highest Daily  11.8  10.2  32.6
 Monthly Total  31.4  27.2  65.0  ,
                           Jan            Feb             Mar             Apr  \
 Statistic
 Mean                    102.2          117.0           129.6           128.8
 Median                   79.8           92.3            99.1            98.8
 Highest Daily  191.017th 1988  243.63rd 1990  280.728th 1942  191.029th 1860

                           May             Jun            Jul            Aug  \
 Statistic
 Mean                    119.2           133.0           97.1           81.1
 Median                   90.8           101.8           74.3           54.9
 Highest Daily  212.328th 1889  150.611th 1991  198.17th 1931  327.66th 1986

                           Sep             Oct            Nov            Dec
 Statistic
 Mean                     68.4            76.4           83.8           77.6
 Median                   52.5            55.4           66.9           59.7
 Highest Daily  144.510th 1879  161.813th 1902  234.69th 1984  126.09th 1970  ]

In [32]:
Rain = Rain_Sydney[Rain_Sydney.index == '2016 graph']
Rain

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
2016,,,,,,,,,,,,
Graph,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st,0.0,0.2,0.0,0.0,2.8,29.4,0.0,0.0,0.0,0.0,0.0,0.0
2nd,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.4,14.4,0.0,0.0,0.2
3rd,0.0,0.0,0.0,0.0,0.0,0.2,0.0,24.8,23.4,0.0,0.0,0.0
4th,15.0,10.8,0.0,94.4,0.0,64.4,0.0,61.0,0.0,0.0,0.0,0.0
5th,34.2,3.6,0.0,6.4,0.0,93.8,4.8,4.0,0.0,0.0,0.0,0.4
6th,51.4,1.8,0.0,0.0,0.0,68.4,0.2,1.8,0.0,0.0,0.0,3.2
7th,41.4,0.0,0.0,0.2,0.0,0.0,29.4,0.6,0.0,0.0,0.0,7.8
8th,0.4,0.0,0.0,0.0,0.0,0.0,22.4,0.0,0.0,0.2,0.0,0.2
9th,0.0,0.0,0.0,0.4,1.6,0.2,2.2,0.0,0.0,0.0,2.0,0.4
10th,0.0,0.2,0.0,0.0,0.0,0.2,1.0,0.0,1.2,0.0,10.2,0.0
11th,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.8,0.0,0.0
12th,0.0,0.0,0.0,8.2,0.0,0.0,0.2,0.0,0.0,0.0,9.0,0.0
13th,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,0.0,4.4,0.0,0.0
14th,0.0,0.0,0.0,0.6,0.0,0.0,0.0,0.0,5.8,0.2,0.0,0.0
15th,34.0,0.0,16.8,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,8.2
16th,5.4,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.6
17th,0.0,0.0,13.6,0.0,0.0,0.0,0.8,0.0,0.0,0.0,0.0,10.4
18th,0.0,0.0,3.4,2.0,0.0,5.0,0.0,0.0,0.0,3.0,0.0,0.0
19th,0.0,0.0,4.8,15.0,0.0,0.4,0.2,0.0,13.4,0.2,0.0,0.0
20th,0.0,0.0,0.2,15.8,0.0,38.8,17.0,0.4,0.0,0.0,0.0,0.0
21st,0.0,6.0,61.2,0.0,0.0,0.0,20.4,0.0,0.0,0.0,0.0,0.0
22nd,30.6,1.2,25.4,0.0,0.0,0.0,0.0,0.0,2.0,11.8,0.0,0.0
23rd,13.0,0.0,1.6,6.6,0.0,0.0,6.0,1.8,0.6,0.6,0.0,0.0
24th,0.0,0.0,0.0,3.8,0.0,0.0,0.0,2.4,0.0,0.8,5.4,0.0
25th,0.0,0.0,0.0,0.0,0.0,0.6,0.0,52.8,3.4,0.0,0.0,1.6
26th,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,4.0,0.0,0.0,0.0
27th,2.2,0.0,0.2,0.0,0.2,0.0,0.0,1.4,0.0,0.0,0.0,0.0
28th,0.4,0.0,34.8,0.0,0.0,2.4,0.0,0.0,0.0,1.4,0.0,0.0
29th,0.0,0.0,0.0,0.0,2.2,0.2,0.0,0.0,1.4,3.2,0.0,0.0
30th,9.0,NaN,7.0,0.0,0.2,0.0,0.0,0.0,0.4,0.2,0.0,0.0
31st,12.8,NaN,1.2,NaN,0.0,NaN,0.0,0.0,NaN,1.6,NaN,0.0
Highest Daily,51.4,10.8,61.2,94.4,2.8,93.8,29.4,61.0,23.4,11.8,10.2,32.6
Monthly Total,249.8,25.8,193.2,155.0,7.2,305.0,104.6,151.4,70.0,31.4,27.2,65.0

In [34]:
mt=Rain[Rain.index == 'Monthly Total'].sum()
mt

Jan    249.8
Feb     25.8
Mar    193.2
Apr    155.0
May      7.2
Jun    305.0
Jul    104.6
Aug    151.4
Sep     70.0
Oct     31.4
Nov     27.2
Dec     65.0
dtype: float64

In [35]:
mt.sum()

1385.6000000000001

Sydney Annual Rain fall = 1385.6mm